/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedMeuEstoqueRouteImport } from './routes/_authenticated/meu-estoque'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedExtrairConcorrenteRouteImport } from './routes/_authenticated/extrair-concorrente'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConcorrentesRouteImport } from './routes/_authenticated/concorrentes'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuEstoqueRoute = AuthenticatedMeuEstoqueRouteImport.update({
  id: '/meu-estoque',
  path: '/meu-estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtrairConcorrenteRoute =
  AuthenticatedExtrairConcorrenteRouteImport.update({
    id: '/extrair-concorrente',
    path: '/extrair-concorrente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcorrentesRoute =
  AuthenticatedConcorrentesRouteImport.update({
    id: '/concorrentes',
    path: '/concorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/extrair-concorrente': typeof AuthenticatedExtrairConcorrenteRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/extrair-concorrente': typeof AuthenticatedExtrairConcorrenteRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/extrair-concorrente': typeof AuthenticatedExtrairConcorrenteRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/administracao'
    | '/comparar'
    | '/concorrentes'
    | '/configuracoes'
    | '/extrair-concorrente'
    | '/importacoes'
    | '/meu-estoque'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/administracao'
    | '/comparar'
    | '/concorrentes'
    | '/configuracoes'
    | '/extrair-concorrente'
    | '/importacoes'
    | '/meu-estoque'
    | '/relatorios'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/administracao'
    | '/_authenticated/comparar'
    | '/_authenticated/concorrentes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/extrair-concorrente'
    | '/_authenticated/importacoes'
    | '/_authenticated/meu-estoque'
    | '/_authenticated/relatorios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-estoque': {
      id: '/_authenticated/meu-estoque'
      path: '/meu-estoque'
      fullPath: '/meu-estoque'
      preLoaderRoute: typeof AuthenticatedMeuEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrair-concorrente': {
      id: '/_authenticated/extrair-concorrente'
      path: '/extrair-concorrente'
      fullPath: '/extrair-concorrente'
      preLoaderRoute: typeof AuthenticatedExtrairConcorrenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concorrentes': {
      id: '/_authenticated/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof AuthenticatedConcorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedConcorrentesRoute: typeof AuthenticatedConcorrentesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedExtrairConcorrenteRoute: typeof AuthenticatedExtrairConcorrenteRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedMeuEstoqueRoute: typeof AuthenticatedMeuEstoqueRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedConcorrentesRoute: AuthenticatedConcorrentesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedExtrairConcorrenteRoute: AuthenticatedExtrairConcorrenteRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedMeuEstoqueRoute: AuthenticatedMeuEstoqueRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
