/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedMovimentacoesMercadoRouteImport } from './routes/_authenticated/movimentacoes-mercado'
import { Route as AuthenticatedMonitorMercadoRouteImport } from './routes/_authenticated/monitor-mercado'
import { Route as AuthenticatedMeuEstoqueRouteImport } from './routes/_authenticated/meu-estoque'
import { Route as AuthenticatedLocalizarConcorrentesRouteImport } from './routes/_authenticated/localizar-concorrentes'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedHistoricoMercadoRouteImport } from './routes/_authenticated/historico-mercado'
import { Route as AuthenticatedEstrategiaPrecoRouteImport } from './routes/_authenticated/estrategia-preco'
import { Route as AuthenticatedDiagnosticoSincronizacaoRouteImport } from './routes/_authenticated/diagnostico-sincronizacao'
import { Route as AuthenticatedDiagnosticoExtracaoRouteImport } from './routes/_authenticated/diagnostico-extracao'
import { Route as AuthenticatedConsultaMercadoRouteImport } from './routes/_authenticated/consulta-mercado'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConcorrentesRouteImport } from './routes/_authenticated/concorrentes'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedCentralConsultaRouteImport } from './routes/_authenticated/central-consulta'
import { Route as AuthenticatedAlteracoesMercadoRouteImport } from './routes/_authenticated/alteracoes-mercado'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedVeiculoIdRouteImport } from './routes/_authenticated/veiculo.$id'
import { Route as AuthenticatedConcorrenteIdRouteImport } from './routes/_authenticated/concorrente.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesMercadoRoute =
  AuthenticatedMovimentacoesMercadoRouteImport.update({
    id: '/movimentacoes-mercado',
    path: '/movimentacoes-mercado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorMercadoRoute =
  AuthenticatedMonitorMercadoRouteImport.update({
    id: '/monitor-mercado',
    path: '/monitor-mercado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuEstoqueRoute = AuthenticatedMeuEstoqueRouteImport.update({
  id: '/meu-estoque',
  path: '/meu-estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalizarConcorrentesRoute =
  AuthenticatedLocalizarConcorrentesRouteImport.update({
    id: '/localizar-concorrentes',
    path: '/localizar-concorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoMercadoRoute =
  AuthenticatedHistoricoMercadoRouteImport.update({
    id: '/historico-mercado',
    path: '/historico-mercado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstrategiaPrecoRoute =
  AuthenticatedEstrategiaPrecoRouteImport.update({
    id: '/estrategia-preco',
    path: '/estrategia-preco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoSincronizacaoRoute =
  AuthenticatedDiagnosticoSincronizacaoRouteImport.update({
    id: '/diagnostico-sincronizacao',
    path: '/diagnostico-sincronizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticoExtracaoRoute =
  AuthenticatedDiagnosticoExtracaoRouteImport.update({
    id: '/diagnostico-extracao',
    path: '/diagnostico-extracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultaMercadoRoute =
  AuthenticatedConsultaMercadoRouteImport.update({
    id: '/consulta-mercado',
    path: '/consulta-mercado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConcorrentesRoute =
  AuthenticatedConcorrentesRouteImport.update({
    id: '/concorrentes',
    path: '/concorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentralConsultaRoute =
  AuthenticatedCentralConsultaRouteImport.update({
    id: '/central-consulta',
    path: '/central-consulta',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlteracoesMercadoRoute =
  AuthenticatedAlteracoesMercadoRouteImport.update({
    id: '/alteracoes-mercado',
    path: '/alteracoes-mercado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVeiculoIdRoute = AuthenticatedVeiculoIdRouteImport.update({
  id: '/veiculo/$id',
  path: '/veiculo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcorrenteIdRoute =
  AuthenticatedConcorrenteIdRouteImport.update({
    id: '/concorrente/$id',
    path: '/concorrente/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alteracoes-mercado': typeof AuthenticatedAlteracoesMercadoRoute
  '/central-consulta': typeof AuthenticatedCentralConsultaRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consulta-mercado': typeof AuthenticatedConsultaMercadoRoute
  '/diagnostico-extracao': typeof AuthenticatedDiagnosticoExtracaoRoute
  '/diagnostico-sincronizacao': typeof AuthenticatedDiagnosticoSincronizacaoRoute
  '/estrategia-preco': typeof AuthenticatedEstrategiaPrecoRoute
  '/historico-mercado': typeof AuthenticatedHistoricoMercadoRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/localizar-concorrentes': typeof AuthenticatedLocalizarConcorrentesRoute
  '/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/monitor-mercado': typeof AuthenticatedMonitorMercadoRoute
  '/movimentacoes-mercado': typeof AuthenticatedMovimentacoesMercadoRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/concorrente/$id': typeof AuthenticatedConcorrenteIdRoute
  '/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/alteracoes-mercado': typeof AuthenticatedAlteracoesMercadoRoute
  '/central-consulta': typeof AuthenticatedCentralConsultaRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consulta-mercado': typeof AuthenticatedConsultaMercadoRoute
  '/diagnostico-extracao': typeof AuthenticatedDiagnosticoExtracaoRoute
  '/diagnostico-sincronizacao': typeof AuthenticatedDiagnosticoSincronizacaoRoute
  '/estrategia-preco': typeof AuthenticatedEstrategiaPrecoRoute
  '/historico-mercado': typeof AuthenticatedHistoricoMercadoRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/localizar-concorrentes': typeof AuthenticatedLocalizarConcorrentesRoute
  '/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/monitor-mercado': typeof AuthenticatedMonitorMercadoRoute
  '/movimentacoes-mercado': typeof AuthenticatedMovimentacoesMercadoRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/concorrente/$id': typeof AuthenticatedConcorrenteIdRoute
  '/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/alteracoes-mercado': typeof AuthenticatedAlteracoesMercadoRoute
  '/_authenticated/central-consulta': typeof AuthenticatedCentralConsultaRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/concorrentes': typeof AuthenticatedConcorrentesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consulta-mercado': typeof AuthenticatedConsultaMercadoRoute
  '/_authenticated/diagnostico-extracao': typeof AuthenticatedDiagnosticoExtracaoRoute
  '/_authenticated/diagnostico-sincronizacao': typeof AuthenticatedDiagnosticoSincronizacaoRoute
  '/_authenticated/estrategia-preco': typeof AuthenticatedEstrategiaPrecoRoute
  '/_authenticated/historico-mercado': typeof AuthenticatedHistoricoMercadoRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/localizar-concorrentes': typeof AuthenticatedLocalizarConcorrentesRoute
  '/_authenticated/meu-estoque': typeof AuthenticatedMeuEstoqueRoute
  '/_authenticated/monitor-mercado': typeof AuthenticatedMonitorMercadoRoute
  '/_authenticated/movimentacoes-mercado': typeof AuthenticatedMovimentacoesMercadoRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/concorrente/$id': typeof AuthenticatedConcorrenteIdRoute
  '/_authenticated/veiculo/$id': typeof AuthenticatedVeiculoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/sitemap.xml'
    | '/administracao'
    | '/alteracoes-mercado'
    | '/central-consulta'
    | '/comparar'
    | '/concorrentes'
    | '/configuracoes'
    | '/consulta-mercado'
    | '/diagnostico-extracao'
    | '/diagnostico-sincronizacao'
    | '/estrategia-preco'
    | '/historico-mercado'
    | '/importacoes'
    | '/localizar-concorrentes'
    | '/meu-estoque'
    | '/monitor-mercado'
    | '/movimentacoes-mercado'
    | '/operacoes'
    | '/concorrente/$id'
    | '/veiculo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/sitemap.xml'
    | '/administracao'
    | '/alteracoes-mercado'
    | '/central-consulta'
    | '/comparar'
    | '/concorrentes'
    | '/configuracoes'
    | '/consulta-mercado'
    | '/diagnostico-extracao'
    | '/diagnostico-sincronizacao'
    | '/estrategia-preco'
    | '/historico-mercado'
    | '/importacoes'
    | '/localizar-concorrentes'
    | '/meu-estoque'
    | '/monitor-mercado'
    | '/movimentacoes-mercado'
    | '/operacoes'
    | '/'
    | '/concorrente/$id'
    | '/veiculo/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/administracao'
    | '/_authenticated/alteracoes-mercado'
    | '/_authenticated/central-consulta'
    | '/_authenticated/comparar'
    | '/_authenticated/concorrentes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consulta-mercado'
    | '/_authenticated/diagnostico-extracao'
    | '/_authenticated/diagnostico-sincronizacao'
    | '/_authenticated/estrategia-preco'
    | '/_authenticated/historico-mercado'
    | '/_authenticated/importacoes'
    | '/_authenticated/localizar-concorrentes'
    | '/_authenticated/meu-estoque'
    | '/_authenticated/monitor-mercado'
    | '/_authenticated/movimentacoes-mercado'
    | '/_authenticated/operacoes'
    | '/_authenticated/'
    | '/_authenticated/concorrente/$id'
    | '/_authenticated/veiculo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes-mercado': {
      id: '/_authenticated/movimentacoes-mercado'
      path: '/movimentacoes-mercado'
      fullPath: '/movimentacoes-mercado'
      preLoaderRoute: typeof AuthenticatedMovimentacoesMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitor-mercado': {
      id: '/_authenticated/monitor-mercado'
      path: '/monitor-mercado'
      fullPath: '/monitor-mercado'
      preLoaderRoute: typeof AuthenticatedMonitorMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-estoque': {
      id: '/_authenticated/meu-estoque'
      path: '/meu-estoque'
      fullPath: '/meu-estoque'
      preLoaderRoute: typeof AuthenticatedMeuEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/localizar-concorrentes': {
      id: '/_authenticated/localizar-concorrentes'
      path: '/localizar-concorrentes'
      fullPath: '/localizar-concorrentes'
      preLoaderRoute: typeof AuthenticatedLocalizarConcorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-mercado': {
      id: '/_authenticated/historico-mercado'
      path: '/historico-mercado'
      fullPath: '/historico-mercado'
      preLoaderRoute: typeof AuthenticatedHistoricoMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategia-preco': {
      id: '/_authenticated/estrategia-preco'
      path: '/estrategia-preco'
      fullPath: '/estrategia-preco'
      preLoaderRoute: typeof AuthenticatedEstrategiaPrecoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico-sincronizacao': {
      id: '/_authenticated/diagnostico-sincronizacao'
      path: '/diagnostico-sincronizacao'
      fullPath: '/diagnostico-sincronizacao'
      preLoaderRoute: typeof AuthenticatedDiagnosticoSincronizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico-extracao': {
      id: '/_authenticated/diagnostico-extracao'
      path: '/diagnostico-extracao'
      fullPath: '/diagnostico-extracao'
      preLoaderRoute: typeof AuthenticatedDiagnosticoExtracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consulta-mercado': {
      id: '/_authenticated/consulta-mercado'
      path: '/consulta-mercado'
      fullPath: '/consulta-mercado'
      preLoaderRoute: typeof AuthenticatedConsultaMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concorrentes': {
      id: '/_authenticated/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof AuthenticatedConcorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central-consulta': {
      id: '/_authenticated/central-consulta'
      path: '/central-consulta'
      fullPath: '/central-consulta'
      preLoaderRoute: typeof AuthenticatedCentralConsultaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alteracoes-mercado': {
      id: '/_authenticated/alteracoes-mercado'
      path: '/alteracoes-mercado'
      fullPath: '/alteracoes-mercado'
      preLoaderRoute: typeof AuthenticatedAlteracoesMercadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculo/$id': {
      id: '/_authenticated/veiculo/$id'
      path: '/veiculo/$id'
      fullPath: '/veiculo/$id'
      preLoaderRoute: typeof AuthenticatedVeiculoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concorrente/$id': {
      id: '/_authenticated/concorrente/$id'
      path: '/concorrente/$id'
      fullPath: '/concorrente/$id'
      preLoaderRoute: typeof AuthenticatedConcorrenteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAlteracoesMercadoRoute: typeof AuthenticatedAlteracoesMercadoRoute
  AuthenticatedCentralConsultaRoute: typeof AuthenticatedCentralConsultaRoute
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedConcorrentesRoute: typeof AuthenticatedConcorrentesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsultaMercadoRoute: typeof AuthenticatedConsultaMercadoRoute
  AuthenticatedDiagnosticoExtracaoRoute: typeof AuthenticatedDiagnosticoExtracaoRoute
  AuthenticatedDiagnosticoSincronizacaoRoute: typeof AuthenticatedDiagnosticoSincronizacaoRoute
  AuthenticatedEstrategiaPrecoRoute: typeof AuthenticatedEstrategiaPrecoRoute
  AuthenticatedHistoricoMercadoRoute: typeof AuthenticatedHistoricoMercadoRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedLocalizarConcorrentesRoute: typeof AuthenticatedLocalizarConcorrentesRoute
  AuthenticatedMeuEstoqueRoute: typeof AuthenticatedMeuEstoqueRoute
  AuthenticatedMonitorMercadoRoute: typeof AuthenticatedMonitorMercadoRoute
  AuthenticatedMovimentacoesMercadoRoute: typeof AuthenticatedMovimentacoesMercadoRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConcorrenteIdRoute: typeof AuthenticatedConcorrenteIdRoute
  AuthenticatedVeiculoIdRoute: typeof AuthenticatedVeiculoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAlteracoesMercadoRoute: AuthenticatedAlteracoesMercadoRoute,
  AuthenticatedCentralConsultaRoute: AuthenticatedCentralConsultaRoute,
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedConcorrentesRoute: AuthenticatedConcorrentesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsultaMercadoRoute: AuthenticatedConsultaMercadoRoute,
  AuthenticatedDiagnosticoExtracaoRoute: AuthenticatedDiagnosticoExtracaoRoute,
  AuthenticatedDiagnosticoSincronizacaoRoute:
    AuthenticatedDiagnosticoSincronizacaoRoute,
  AuthenticatedEstrategiaPrecoRoute: AuthenticatedEstrategiaPrecoRoute,
  AuthenticatedHistoricoMercadoRoute: AuthenticatedHistoricoMercadoRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedLocalizarConcorrentesRoute:
    AuthenticatedLocalizarConcorrentesRoute,
  AuthenticatedMeuEstoqueRoute: AuthenticatedMeuEstoqueRoute,
  AuthenticatedMonitorMercadoRoute: AuthenticatedMonitorMercadoRoute,
  AuthenticatedMovimentacoesMercadoRoute:
    AuthenticatedMovimentacoesMercadoRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConcorrenteIdRoute: AuthenticatedConcorrenteIdRoute,
  AuthenticatedVeiculoIdRoute: AuthenticatedVeiculoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
